### ISSUE TITLE
Only works if add ".default" in the required.

### ISSUE THREAD

**Issue by nelbren** [kamronbatman/joi-password-complexity#37]
Hi!

- The current version fails, check if it is something I am missing in my code or dependency. 
  **See a demo of the failure here:** [https://runkit.com/nelbren/joi-password-complexity-try-1](https://runkit.com/nelbren/joi-password-complexity-try-1)
  ![joi-password-complexity-try-1](https://user-images.githubusercontent.com/17136255/100882657-0daa1380-3475-11eb-8375-56a71d2cfa6a.png)

- By making the **adjustment** indicated on this page [https://stackoverflow.com/a/64866700/6913786](https://stackoverflow.com/a/64866700/6913786), **it works**.
  **See a demo of when it works here:** [https://runkit.com/nelbren/joi-password-complexity-try-2](https://runkit.com/nelbren/joi-password-complexity-try-2)
  ![joi-password-complexity-try-2](https://user-images.githubusercontent.com/17136255/100882536-ed7a5480-3474-11eb-8478-63b767b56b90.png)
Regards!

**Comment by kamronbatman** [comment]
That is most likely because of import syntax as cjs. I think I might need to release it in two formats, one being a native cjs. Not sure how to do it off the top of my head.
If anyone knows let me know or make a PR. Otherwise I'll research it.

Thanks!

**Comment by cyrilcisco** [comment]
Hello,
I have the same issue as nelbren.
If I don't add the .default after require("joi-password-complexity") to import the _default const that you declared in index.d.ts
I have a TypeError: passwordComplexity is not a function.

Without the .default the JoiPasswordComplexity interface seems to be imported instead of the passwordComplexity() function

I don't understand where the error comes from. I asked me if it is not from the line 114 of index.ts

Regards. Thanks for Joi.

**Comment by cyrilcisco** [comment]
or is it because I'm using nodejs v12.19.0 and it's javascript and not typescript like your package?

**Comment by kamronbatman** [comment]
I think there needs to be a dual build, one for cjs, and one for imports. I haven't had time to figure out what is needed to build it. If anyone wants to tackle this and make a PR, I would greatly appreciate it.

Also thank you for your interest in this project! :)

**Comment by kamronbatman** [comment]
@nelbren sorry for the late response. Please test #40 and see if that works.
