### ISSUE TITLE
uppercase and lowercase not working

### ISSUE THREAD

**Issue by isimmons** [kamronbatman/joi-password-complexity#49]
joi v17.4.2
joi-password-complexity v5.1.0
node v16.13.0

The following options is allowing password 123@456 

```
password: new pwComplexity({
            min: 5,
            max: 255,
            lowercase: 2,
            uppercase: 1,
            numeric: 1,
            symbol: 1,
            requirementCount: 3
        }).required()
```

 If my understanding is correct, I should have at least 2 lowercase letters, at least 1 uppercase letter, at least 1 number, and at least 1 symbol

I read in the src code to find what requirementCount is for and am confused about it. Don't I want all requirements listed to be met? I tried increasing and decreasing this number but it makes no difference. 

I also tried removing the new keyword and .required() method and direct copy pasting from the example in the readme.

Only when I leave the options out and it runs the defaults do uppercase and lowercase work.

**Comment by kamronbatman** [comment]
Thanks I'll look into it!

**Comment by kamronbatman** [comment]
@isimmons, the way to interpret your example is the following:
"You must pass _at least 3 of the following 4 requirements_"
This means if your password is `PEOPLE1!`, it will be valid since it passes the following 3 requirements:
* 1 uppercase
* 1 numeric
* 1 symbol

if you want all of them, then set requiredCount to 4, or don't specify it and it will default to 4.

Meanwhile, I'll double check the tests with your situation to make sure it is working properly.
